version: '3.8'

services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - ${DB_PORT}:${DB_PORT}
